{ 
   // inspect the TTree generated by make_TTree.C 
   // saved in the root file     tree1.root

   TFile *f = new TFile("tree1.root");
   TTree *t1 = (TTree*)f->Get("t1");
//         MMx, MMy, MMz,     IIv 
//         are "the interface" to the branches  
//         here they have different names; they are arbitrary
//         NOT CONNECTED with  the TTree 
   Float_t MMx, MMy, MMz;   int MMv;

   t1->SetBranchAddress("px",&MMx);  //t1->Branch("px",&PPx,"px/F");
   t1->SetBranchAddress("py",&MMy);
   t1->SetBranchAddress("pz",&MMz);
   t1->SetBranchAddress("ev",&MMv);
   //read all entries 
   int nentries = t1->GetEntries();  // How many "levels" in the tree

   for (int i=0; i<nentries; i++) {
   
      t1->GetEntry(i);     // copy i-th level to the interface       
      printf(" %4d %10.4f %10.4f %10.4f\n", MMv, MMx, MMy, MMz);
   }
   new TBrowser ();
   t1->StartViewer();   // You can also use the 
                        // TBrowser and Tree Viewer
   
}
